name: aladin_m3u_parser_pro
description: "Aladin M3U Parser & Analyzer"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Buradaki assets kısmını sildik, aşağıya taşıdık.
  flutter_riverpod: ^2.5.1
  file_picker: ^8.0.0
  excel: ^4.0.0
  path_provider: ^2.1.0
  share_plus: ^10.0.0
  url_launcher: ^6.3.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  # Doğru yer burası:
  assets:
    - assets/logo.png
    - assets/aladin_icon_logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/aladin_icon_logo.png" # ikon dosyanın yolu
  adaptive_icon_background: "#0F172A" # Uygulama temanla uyumlu koyu arka plan
  adaptive_icon_foreground: "assets/aladin_icon_logo.png"